/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: Juan Martinez Sanjurjo (https://sketchfab.com/JuanSanjurjo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/advanced-game-characters-week-2-jacket-8f211f057bb24f5db17ca659553b716b
title: Advanced Game Characters - Week 2 Jacket
*/

import React, { useRef } from "react";
import { useLoader } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { draco } from "drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useLoader(
    GLTFLoader,
    `../${props.permalink}/scene.gltf`,
    draco("/draco-gltf/")
  );

  return (
    <group ref={group} dispose={null} castShadow receiveShadow>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            material={materials.Jacket_Lv2_Jacket}
            material-color={props.color}
            geometry={nodes.defaultMaterial.geometry}
          />
        </group>
      </group>
    </group>
  );
}
